// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14/02/2025, 19.42.26
const configMerger = require("D:/Github/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Github/CRUD/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Github/CRUD/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Github/CRUD/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Github/CRUD/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Github/CRUD/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Github/CRUD/plugins/**/*.{js,ts,mjs}","D:/Github/CRUD/composables/**/*.{js,ts,mjs}","D:/Github/CRUD/utils/**/*.{js,ts,mjs}","D:/Github/CRUD/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Github/CRUD/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Github/CRUD/app.config.{js,ts,mjs}"] }));

module.exports = config
